"""
DevOps Butler - Plan Validator
Validates Claude-generated deployment plans before execution.
Catches common errors to prevent runtime failures.
"""

import re
import json
import logging
from typing import Dict, List, Any, Tuple

from config.logging_config import get_logger

logger = get_logger("plan_validator")

# ── Valid AWS instance types ────────────────────────────────────────────
VALID_EC2_FAMILIES = {
    "t2", "t3", "t3a", "m5", "m5a", "m6i", "m6a", "c5", "c5a", "c6i",
    "r5", "r5a", "r6i", "p3", "g4", "g5",
}
VALID_EC2_SIZES = {
    "nano", "micro", "small", "medium", "large",
    "xlarge", "2xlarge", "4xlarge", "8xlarge", "12xlarge", "16xlarge", "24xlarge",
}

VALID_RDS_FAMILIES = {"db.t3", "db.t4g", "db.m5", "db.m6g", "db.r5", "db.r6g"}
VALID_CACHE_FAMILIES = {"cache.t3", "cache.t4g", "cache.m5", "cache.r5", "cache.r6g"}


class PlanValidator:
    """
    Validates a deployment plan generated by Claude to catch errors
    before they cause runtime failures.
    
    Checks:
    - Instance types are valid
    - Port ranges are valid (1-65535)
    - Required fields exist
    - Security group rules make sense
    - Terraform resource names are valid
    - Docker image tags are valid
    - Cost estimates are reasonable
    """

    def validate(
        self,
        plan: Dict[str, Any],
        budget: float = 100.0,
        trace_id: str = "no-trace",
    ) -> Dict[str, Any]:
        """
        Validate a deployment plan.
        
        Returns:
            {
                "is_valid": True/False,
                "errors": [...],    # Blocking issues
                "warnings": [...],  # Non-blocking concerns
            }
        """
        errors: List[str] = []
        warnings: List[str] = []

        # ── Structural validation ───────────────────────────────────
        if not plan:
            return {"is_valid": False, "errors": ["Empty plan"], "warnings": []}

        if "steps" not in plan and "tasks" not in plan:
            errors.append("Plan has no steps or tasks defined")

        if "strategy" not in plan:
            warnings.append("No deployment strategy specified")

        # ── Step validation ─────────────────────────────────────────
        steps = plan.get("steps", plan.get("tasks", []))
        if isinstance(steps, list):
            for i, step in enumerate(steps):
                step_errors = self._validate_step(step, i)
                errors.extend(step_errors)

        # ── Resource validation ─────────────────────────────────────
        resources = plan.get("resources", [])
        if isinstance(resources, list):
            for resource in resources:
                r_errors, r_warnings = self._validate_resource(resource)
                errors.extend(r_errors)
                warnings.extend(r_warnings)

        # ── Cost validation ─────────────────────────────────────────
        estimated_cost = plan.get("estimated_monthly_cost_usd", 0)
        if estimated_cost > budget:
            errors.append(
                f"Estimated cost ${estimated_cost:.2f} exceeds budget ${budget:.2f}"
            )
        elif estimated_cost > budget * 0.8:
            warnings.append(
                f"Estimated cost ${estimated_cost:.2f} is close to budget ${budget:.2f}"
            )
        elif estimated_cost <= 0:
            warnings.append("No cost estimate provided")

        # ── Generated files validation ──────────────────────────────
        generated_files = plan.get("generated_files", {})
        if isinstance(generated_files, dict):
            for filename, content in generated_files.items():
                if filename.lower() == "dockerfile" or filename.endswith("Dockerfile"):
                    file_warnings = self._validate_dockerfile(content)
                    warnings.extend(file_warnings)
                elif filename.endswith(".tf"):
                    file_warnings = self._validate_terraform(content)
                    warnings.extend(file_warnings)

        is_valid = len(errors) == 0

        result = {
            "is_valid": is_valid,
            "errors": errors,
            "warnings": warnings,
        }

        logger.info(
            f"Plan validation: {'PASS' if is_valid else 'FAIL'} "
            f"({len(errors)} errors, {len(warnings)} warnings)",
            extra={"trace_id": trace_id}
        )

        return result

    def _validate_step(self, step: Dict[str, Any], index: int) -> List[str]:
        """Validate a single step in the plan."""
        errors = []
        prefix = f"Step {index + 1}"

        if not isinstance(step, dict):
            return [f"{prefix}: Invalid step format (not a dict)"]

        if "type" not in step and "description" not in step:
            errors.append(f"{prefix}: Missing both 'type' and 'description'")

        # Validate commands
        commands = step.get("commands", [])
        if isinstance(commands, list):
            for cmd in commands:
                if not isinstance(cmd, str):
                    continue
                # Check for dangerous commands
                dangerous_patterns = [
                    r"rm\s+-rf\s+/\s*$",  # rm -rf /
                    r"mkfs\.",             # format filesystem
                    r"dd\s+if=",           # disk destroyer
                ]
                for pattern in dangerous_patterns:
                    if re.search(pattern, cmd):
                        errors.append(f"{prefix}: Potentially dangerous command: {cmd}")

        return errors

    def _validate_resource(self, resource: Dict[str, Any]) -> Tuple[List[str], List[str]]:
        """Validate a resource definition."""
        errors = []
        warnings = []

        r_type = resource.get("type", "").lower()
        instance_type = resource.get("instance_type", "")

        if r_type == "ec2" and instance_type:
            if not self._is_valid_ec2_type(instance_type):
                warnings.append(f"Potentially invalid EC2 instance type: {instance_type}")

        elif r_type == "rds" and instance_type:
            if not self._is_valid_rds_type(instance_type):
                warnings.append(f"Potentially invalid RDS instance type: {instance_type}")

        # Validate port
        port = resource.get("port", resource.get("container_port"))
        if port is not None and isinstance(port, (int, str)):
            try:
                port_int = int(port)
                if port_int < 1 or port_int > 65535:
                    errors.append(f"Invalid port number: {port_int}")
            except (ValueError, TypeError):
                errors.append(f"Invalid port value: {port}")

        return errors, warnings

    def _validate_dockerfile(self, content: str) -> List[str]:
        """Validate Dockerfile content for common issues."""
        warnings = []
        if not content:
            return warnings

        if "FROM" not in content.upper():
            warnings.append("Dockerfile missing FROM instruction")
        
        if "LATEST" in content.upper() and "FROM" in content.upper():
            warnings.append("Dockerfile uses :latest tag — consider pinning version")

        if "COPY . ." in content and "COPY requirements" not in content and "COPY package" not in content:
            warnings.append("Dockerfile copies everything before deps — poor layer caching")

        return warnings

    def _validate_terraform(self, content: str) -> List[str]:
        """Validate Terraform content for common issues."""
        warnings = []
        if not content:
            return warnings

        if "hardcoded" in content.lower() or re.search(r'password\s*=\s*"[^"]+', content):
            warnings.append("Terraform may contain hardcoded secrets")

        if "provider" not in content.lower():
            warnings.append("Terraform file missing provider block")

        return warnings

    def _is_valid_ec2_type(self, instance_type: str) -> bool:
        """Check if EC2 instance type looks valid."""
        parts = instance_type.split(".")
        if len(parts) != 2:
            return False
        family, size = parts
        return family in VALID_EC2_FAMILIES and size in VALID_EC2_SIZES

    def _is_valid_rds_type(self, instance_type: str) -> bool:
        """Check if RDS instance type looks valid."""
        for family in VALID_RDS_FAMILIES:
            if instance_type.startswith(family):
                return True
        return False
